version: "3.9"

services:
    web:
        build:
            dockerfile: Dockerfile
            args:
                user: crudify
                uid: 1000
        image: digitalocean.com/php
        container_name: crudify-package
        restart: unless-stopped
        tty: true
        ports:
            - "8080:80"
        working_dir: /var/www
        volumes:
            - .:/var/www
